USE projeto_api;

CREATE TABLE users (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(120) NOT NULL,
email VARCHAR(190) NOT NULL UNIQUE,
active TINYINT(1) NOT NULL DEFAULT 1,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tasks (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(180) NOT NULL,
category VARCHAR(100) NOT NULL,
done TINYINT(1) NOT NULL DEFAULT 0,
date_conclusion DATE NULL,
user_id INT UNSIGNED NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_tasks_user FOREIGN KEY (user_id)
REFERENCES users(id)
ON UPDATE CASCADE
ON DELETE RESTRICT
);

CREATE TABLE tags (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(80) NOT NULL UNIQUE,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE task_tags (
task_id INT UNSIGNED NOT NULL,
tag_id INT UNSIGNED NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (task_id, tag_id),
CONSTRAINT fk_task_tags_task FOREIGN KEY (task_id)
REFERENCES tasks(id)
ON UPDATE CASCADE
ON DELETE CASCADE,
CONSTRAINT fk_task_tags_tag FOREIGN KEY (tag_id)
REFERENCES tags(id)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE comments (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
task_id INT UNSIGNED NOT NULL,
user_id INT UNSIGNED NOT NULL,
content TEXT NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_comments_task FOREIGN KEY (task_id)
REFERENCES tasks(id)
ON UPDATE CASCADE
ON DELETE CASCADE,
CONSTRAINT fk_comments_user FOREIGN KEY (user_id)
REFERENCES users(id)
ON UPDATE CASCADE
ON DELETE RESTRICT
);

CREATE INDEX idx_tasks_user_id ON tasks (user_id);

CREATE INDEX idx_comments_task_id ON comments (task_id);

CREATE INDEX idx_comments_user_id ON comments (user_id);
